In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 1. covid_1.csv과 covid_2.csv를 데이터프레임으로 불러오기

### 2. 두 데이터 프레임을 합치기

### 3. who.csv를 읽어 들여 조인하기

### 4. Death/Checked를 통해 확진자 수에 대한 사망자 수 비율을 구해 TravelRisk를 형성하라.

### 5. Describe()함수로 25% 지점과 50% 지점 75%지점을 확인하라.

### 6. TravelRisk가 25%지점 이하라면 Class를 0으로 지정, 25% 이상이라면 1로 지정, 50% 이상이라면 2로 지정하라.

### 7. 1~6까지 처리가 다되었으면 covid19.csv로 데이터를 저장하라.

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/2021_2학기_데이터분석과머신러닝/Pandas_Matplotlib 실습

/content/drive/MyDrive/Colab Notebooks/2021_2학기_데이터분석과머신러닝/Pandas_Matplotlib 실습

In [ ]:
df1 = pd.read_csv('covid_1.csv')
df2 = pd.read_csv('covid_2.csv')
df3 = pd.read_csv('who.csv')

In [ ]:
print(df1.columns)
print(df2.columns)
print(df3.columns)

Index(['Country', 'Checked', 'Death'], dtype='object')
Index(['Country', 'Checked', 'Death'], dtype='object')
Index(['WHO', 'Country'], dtype='object')

In [ ]:
df1.head()

        Country  Checked  Death
0       Algeria    27973   1163
1        Angola      950     41
2         Benin     1770     35
3      Botswana      739      2
4  Burkina Faso     1100     53

In [ ]:
df2.head()

        Country  Checked  Death
0          Oman    77058    393
1      Pakistan   274289   5842
2         Qatar   109597    165
3  Saudi Arabia   268934   2760
4       Somalia     3196     93

In [ ]:
df = pd.concat([df1, df2])
df = df.reset_index(drop = True)
df

          Country  Checked  Death
0         Algeria    27973   1163
1          Angola      950     41
2           Benin     1770     35
3        Botswana      739      2
4    Burkina Faso     1100     53
..            ...      ...    ...
181   Philippines    82040   1945
182     Singapore    50838     27
183   South Korea    14203    300
184       Taiwan*      462      7
185       Vietnam      431      0

[186 rows x 3 columns]

In [ ]:
df.head()

        Country  Checked  Death
0       Algeria    27973   1163
1        Angola      950     41
2         Benin     1770     35
3      Botswana      739      2
4  Burkina Faso     1100     53

In [ ]:
df_res = pd.merge(df3, df, left_on='Country', right_on='Country')
df_res.head()

      WHO       Country  Checked  Death
0  Africa       Algeria    27973   1163
1  Africa        Angola      950     41
2  Africa         Benin     1770     35
3  Africa      Botswana      739      2
4  Africa  Burkina Faso     1100     53

In [ ]:
df_res['TravelRisk'] = df_res['Death']/df_res['Checked']
df_res.head()

      WHO       Country  Checked  Death  TravelRisk
0  Africa       Algeria    27973   1163    0.041576
1  Africa        Angola      950     41    0.043158
2  Africa         Benin     1770     35    0.019774
3  Africa      Botswana      739      2    0.002706
4  Africa  Burkina Faso     1100     53    0.048182

In [ ]:
df_res.describe()

            Checked          Death  TravelRisk
count  1.860000e+02     186.000000  186.000000
mean   8.849246e+04    3514.623656    0.030274
std    3.843213e+05   14136.113717    0.034619
min    1.000000e+01       0.000000    0.000000
25%    1.107000e+03      18.250000    0.009406
50%    4.970000e+03     103.500000    0.021521
75%    4.082025e+04     741.000000    0.038804
max    4.290259e+06  148011.000000    0.285630

In [ ]:
df_res['Class'] = 0

In [ ]:
df_res.loc[df_res['TravelRisk']<= 0.009406, 'Class'] = 0
df_res.loc[df_res['TravelRisk']> 0.009406, 'Class'] = 1
df_res.loc[df_res['TravelRisk']< 0.021521, 'Class'] = 2

In [ ]:
df_res

                 WHO       Country  Checked  Death  TravelRisk  Class
0             Africa       Algeria    27973   1163    0.041576      1
1             Africa        Angola      950     41    0.043158      1
2             Africa         Benin     1770     35    0.019774      2
3             Africa      Botswana      739      2    0.002706      2
4             Africa  Burkina Faso     1100     53    0.048182      1
..               ...           ...      ...    ...         ...    ...
181  Western Pacific   Philippines    82040   1945    0.023708      1
182  Western Pacific     Singapore    50838     27    0.000531      2
183  Western Pacific   South Korea    14203    300    0.021122      2
184  Western Pacific       Taiwan*      462      7    0.015152      2
185  Western Pacific       Vietnam      431      0    0.000000      2

[186 rows x 6 columns]

In [ ]:
df_res.to_csv('covid19.csv', sep = ',', encoding = 'utf8', index = False)